export const BUSINESS_THEMES = {
  SALON_BARBERIA: {
    primaryBg: 'bg-amber-600',
    primaryText: 'text-amber-600',
    hoverBg: 'hover:bg-amber-700',
    hoverText: 'hover:text-amber-700',
    softBg: 'bg-amber-50',
    softText: 'text-amber-800',
    border: 'border-amber-200',
    ring: 'focus:ring-amber-500 focus:border-amber-500',
    gradient: 'from-stone-900 via-stone-800 to-amber-950',
    accentText: 'text-amber-500',
    badge: 'border-amber-300 bg-amber-50 text-amber-700',
    button: 'bg-stone-900 hover:bg-stone-800 text-white shadow-sm hover:shadow-md transition-all duration-300',
    selectedSlot: 'border-amber-600 bg-amber-600 text-white shadow-md',
  },
  CONSULTORIO: {
    primaryBg: 'bg-teal-600',
    primaryText: 'text-teal-600',
    hoverBg: 'hover:bg-teal-700',
    hoverText: 'hover:text-teal-700',
    softBg: 'bg-teal-50',
    softText: 'text-teal-800',
    border: 'border-teal-200',
    ring: 'focus:ring-teal-500 focus:border-teal-500',
    gradient: 'from-slate-900 via-teal-950 to-slate-950',
    accentText: 'text-teal-400',
    badge: 'border-teal-300 bg-teal-50 text-teal-700',
    button: 'bg-teal-600 hover:bg-teal-700 text-white shadow-sm hover:shadow-md transition-all duration-300',
    selectedSlot: 'border-teal-600 bg-teal-600 text-white shadow-md',
  },
  RESTAURANTE: {
    primaryBg: 'bg-rose-600',
    primaryText: 'text-rose-600',
    hoverBg: 'hover:bg-rose-700',
    hoverText: 'hover:text-rose-700',
    softBg: 'bg-rose-50',
    softText: 'text-rose-800',
    border: 'border-rose-200',
    ring: 'focus:ring-rose-500 focus:border-rose-500',
    gradient: 'from-stone-950 via-rose-950 to-stone-900',
    accentText: 'text-rose-400',
    badge: 'border-rose-300 bg-rose-50 text-rose-700',
    button: 'bg-rose-600 hover:bg-rose-700 text-white shadow-sm hover:shadow-md transition-all duration-300',
    selectedSlot: 'border-rose-600 bg-rose-600 text-white shadow-md',
  },
  HOTEL: {
    primaryBg: 'bg-indigo-700',
    primaryText: 'text-indigo-700',
    hoverBg: 'hover:bg-indigo-800',
    hoverText: 'hover:text-indigo-800',
    softBg: 'bg-indigo-50',
    softText: 'text-indigo-800',
    border: 'border-indigo-200',
    ring: 'focus:ring-indigo-500 focus:border-indigo-500',
    gradient: 'from-slate-950 via-indigo-950 to-slate-900',
    accentText: 'text-indigo-400',
    badge: 'border-indigo-300 bg-indigo-50 text-indigo-700',
    button: 'bg-indigo-900 hover:bg-indigo-950 text-white shadow-sm hover:shadow-md transition-all duration-300',
    selectedSlot: 'border-indigo-700 bg-indigo-700 text-white shadow-md',
  },
  CANCHA_GIMNASIO: {
    primaryBg: 'bg-emerald-600',
    primaryText: 'text-emerald-600',
    hoverBg: 'hover:bg-emerald-700',
    hoverText: 'hover:text-emerald-700',
    softBg: 'bg-emerald-50',
    softText: 'text-emerald-800',
    border: 'border-emerald-200',
    ring: 'focus:ring-emerald-500 focus:border-emerald-500',
    gradient: 'from-zinc-950 via-emerald-950 to-zinc-900',
    accentText: 'text-emerald-400',
    badge: 'border-emerald-300 bg-emerald-50 text-emerald-700',
    button: 'bg-zinc-900 hover:bg-zinc-800 text-white shadow-sm hover:shadow-md transition-all duration-300',
    selectedSlot: 'border-emerald-600 bg-emerald-600 text-white shadow-md',
  },
  GENERICO: {
    primaryBg: 'bg-blue-600',
    primaryText: 'text-blue-600',
    hoverBg: 'hover:bg-blue-700',
    hoverText: 'hover:text-blue-700',
    softBg: 'bg-blue-50',
    softText: 'text-blue-800',
    border: 'border-blue-200',
    ring: 'focus:ring-blue-500 focus:border-blue-500',
    gradient: 'from-slate-950 via-blue-950 to-slate-900',
    accentText: 'text-blue-400',
    badge: 'border-blue-300 bg-blue-50 text-blue-700',
    button: 'bg-slate-900 hover:bg-slate-800 text-white shadow-sm hover:shadow-md transition-all duration-300',
    selectedSlot: 'border-blue-600 bg-blue-600 text-white shadow-md',
  }
};

export function getTheme(type) {
  return BUSINESS_THEMES[type] || BUSINESS_THEMES.GENERICO;
}
